name: "🖥️ Hardware Report Submission"
description: "Share a hardware compatibility report for AlmaLinux M&E / general workflows."
title: "Report: [ID HERE]"
labels: ["hardware-report"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Community Hardware Survey

        Submit your report in **either** of these ways:

        **Option A (recommended): Paste JSON**
        - Open your `almalinux_me_report.json` file
        - Copy/paste the full contents into the JSON field below

        **Option B: Drag & drop the JSON file**
        - Drag `almalinux_me_report.json` into this issue editor
        - GitHub will upload it and insert a link
        - You can leave the JSON field empty *if the file upload is present*

        ✅ If valid, a **Pull Request** will be created for approval.
        🔒 It is added to the public database **only after the PR is merged**.

  - type: input
    id: report_id
    attributes:
      label: Report ID
      description: Enter the unique ID generated by the script (e.g., 7e66c449).
      placeholder: "e.g., 7e66c449"
    validations:
      required: true

  - type: textarea
    id: json_content
    attributes:
      label: JSON Data (optional if you attached the file)
      description: Paste the full content of `almalinux_me_report.json` OR attach the file by drag & drop above.
      placeholder: "Paste the JSON here (optional if you attached the file)…"
      render: json
    validations:
      required: false